#!/bin/sh

MDIR=/.data_servicex
SDIR=$MDIR/setup
LDIR=$MDIR/log
TDIR=$MDIR/tmp

RDIR=run/
LBIN=bin/
GBIN=/usr/local/bin/

lockdir=/tmp/reportService.lock

LMDIR=$LDIR/$(date '+%Y-%m')

if [ -d $LMDIR ]
then
     echo "$LMDIR exists"
     cd $LMDIR
#     sudo encriptFile
#     git add \*.crt
     git add \*.ljp
     git commit -m "root-$(date +"%D %T")"
     git push https://reportlog:1q2w3e4r5t@github.com/reportlog/log_service.git --all
     ret=$?
     if [ $ret -ne 0 ]; then
     git config --global http.sslVerify false
     git push https://reportlog:1q2w3e4r5t@github.com/reportlog/log_service.git --all
     else
     echo "log pushed successfully!!!"
     fi
     cd $HOME
else
     echo "$LMDIR doesn't exists"
fi

sudo rm -rf $lockdir

exit 0
